name: Deploy Lambda

on:
  push:
    branches:
      - main  # or the branch you want to trigger deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Needed for OIDC
      contents: read  # Needed to access repo code

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials via OIDC
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::<960631463855>:role/<GitHub_acction_workflow>
        aws-region: <ap-south-1>

    - name: Deploy Lambda function
      run: |
        zip function.zip lambda_function.py  # zip your function code
        aws lambda update-function-code \
          --function-name ajay_lambda \
          --zip-file fileb://function.zip
